### PR TITLE
patch: Updated tests with new code

### PR DESCRIPTION
**Pull request by alexandrtovmach**

### CODE REVIEW

**Comment by ndbroadbent** [comment]
Hi @alexandrtovmach, thanks for the PR! I also saw that the JS rules have changed, but I'm worried because it looks like the antd config is actually missing now, so the plugin will no longer work.

Even though the tests are passing now, the code doesn't seem to be correct because these lines are missing from the webpack configuration:

```
  expect(jsRule.options.plugins[0]).toEqual([
    "import",
    { libraryName: "antd", libraryDirectory: "es", style: true }
  ]);
```

**Comment by ndbroadbent** [comment]
Basically we need to figure out how to fix the webpack config so that the babel import plugin will still import everything for the `antd` library. I've been struggling with this for a while but haven't been able to figure it out.

The updated test is incorrect, because it is checking for: 

```
loaderMap: {
      svg: {
        ReactComponent: "@svgr/webpack?-svgo,+titleProp,+ref![path]"
      }
    }
```

But this is not the expected behavior, since the rule is meant to look for our `antd` config.

**Comment by alexandrtovmach** [comment]
@ndbroadbent Okay, I see... Maybe someone with more experience in webpack can help with that

**Comment by ndbroadbent** [comment]
Hi @alexandrtovmach, fortunately @Vovan-VE figured out how to fix the tests in PR #23, using the new `mergeWebpackConfig` function. But thanks for your help!

**Comment by alexandrtovmach** [comment]
@ndbroadbent sure, that's great

**Pull request closed without merging**
