### PR TITLE
allow babel-plugin-import options modification

### PR DESCRIPTION
**Pull request by DavidNorena**
Thanks for helping to maintain `craco-antd`!

Before you submit this PR, please check the following:

- 100% test coverage

```
jest --coverage --testPathIgnorePatterns test-app
```

- Code is formatted with Prettier

```
yarn prettier --write "**/*.{js,jsx,json,css,scss,html,md,yml}"
```

- No ESLint warnings

```
yarn eslint --fix --ext .js lib/
```

- No security vulnerabilities in any NPM packages

```
yarn audit
```

You are also welcome to add your GitHub username to the [Contributors](#Contributors) section at the bottom of this README. (_optional_)

**Please don't submit this pull request if it does not meet the above requirements.**

### CODE REVIEW

**Comment by DavidNorena** [comment]
fix for #50

**Comment by ndbroadbent** [comment]
Thanks a lot, this looks great! Unfortunately it looks like there are some security warnings I need to fix on the master branch, but otherwise everything looks good here

**Comment by ndbroadbent** [comment]
I've merged it in, but I will try to fix all the security warnings first before I push out a new version. (hopefully I can do it this weekend)

**Comment by ndbroadbent** [comment]
I've just upgraded react-scripts and all of the other NPM packages to the latest versions and fixed all those security warnings. I've released these changes in version: `1.19.0`. Please try that out and let me know if you run into any issues!

**Pull request merged**
