### PR TITLE
Pin craco-less to < 1.17.0

### PR DESCRIPTION
**Pull request by daniel-hauser**
Fixes https://github.com/DocSpring/craco-antd/issues/33

### CODE REVIEW

**Comment by ndbroadbent** [comment]
Hello, thanks a lot for the PR! 

It looks like there are some security vulnerabilities in the current `yarn.lock`. I would also really appreciate your help if you could please help me update these packages. Thanks a lot for your help!

There is also another PR (#35) that seems to add support for the latest less version.

**Comment by ndbroadbent** [comment]
Hello, thanks again for your help! I've updated craco-less and the less loader to the latest versions, and the changes have been pushed to `craco-antd` version `1.15.0`

**Comment by daniel-hauser** [comment]
@ndbroadbent can you please reopen this PR?

I'll also really appreciate it if you merge it - as my production builds are failing.

Ill open a separate PR for the upgrading of (unrelated to the #33 issue) packages

**Comment by aitsvet** [comment]
Why pin to older version, let's correct this:
https://github.com/DocSpring/craco-antd/pull/37

**Pull request closed without merging**
