### PR TITLE
Pin craco-less to < 1.17.0

### PR DESCRIPTION
**Pull request by daniel-hauser**
This PR is a duplicate of #34 (that was closed when #33 closed)

In addition, ran `yarn upgrade` so now `yarn audit` passes

------

Thanks for helping to maintain `craco-antd`!

Before you submit this PR, please check the following:

- 100% test coverage

```
jest --coverage --testPathIgnorePatterns test-app
```

- Code is formatted with Prettier

```
yarn prettier --write "**/*.{js,jsx,json,css,scss,html,md,yml}"
```

- No ESLint warnings

```
yarn eslint --fix --ext .js lib/
```

- No security vulnerabilities in any NPM packages

```
yarn audit
```

You are also welcome to add your GitHub username to the [Contributors](#Contributors) section at the bottom of this README. (_optional_)

**Please don't submit this pull request if it does not meet the above requirements.**

### CODE REVIEW

**Comment by aitsvet** [comment]
Why pin to older version, let's correct this:
https://github.com/DocSpring/craco-antd/pull/37

**Comment by ndbroadbent** [comment]
Thanks a lot, sorry about the difficulties!

**Comment by daniel-hauser** [comment]
@aitsvet This PR is a hotfix to allow dependants to build without errors, after that its a great idea to fix the code to use the new API

**Comment by ndbroadbent** [comment]
Released in version `1.16.0`. I will also merge #37 now to update less

**Pull request merged**
